# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
 tasks:
     - name: Setup AWS CLI
       before: |
         echo 'Intalling AWS CLI'
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         sudo ./aws/install 
         # Clean up 
         rm -rf awscliv2.zip aws
       init: |
         aws --version
         

